### ISSUE TITLE
'레벨' 구조에 맞춰 DDL을 변경한다

### ISSUE THREAD

**Issue by 0chil** [snack-game/server#105]
DDL 문제로 배포에 실패했습니다 :(
다행히 어플리케이션이 바로 롤백 되었지만, 배포하려면 DDL 작업이 우선되어야 하겠네요.
내일 제가 작업해놓겠습니당

**Comment by Hwanvely** [comment]
아아 확인했슴니다 ㅠㅠ

**Comment by 0chil** [comment]
member DDL을 변경하면서 배포 완료했습니다 :)
DDL 관리 수동으로 계속하는게 맞을지 Flyway같은 migration tool을 사용해야 할지 고민이 되네요..!
