### ISSUE TITLE
현재 존재하는 SPOF를 해결한다

### ISSUE THREAD

**Issue by Hwanvely** [snack-game/server#136]
##  AS-IS

운영 환경 기준 서버의 모든 자원은 한개씩만 존재하였습니다.
이런 이유로 아래의 세가지 부분이 SPOF가 될 것이라 예상하고 해결하려합니다.
1. EC2
2. DB
3. S3

## TO-BE

- [x]  EC2 이중화
- 로그인 방식 변경
- [ ] DB 이중화
- MySQL Replication
- [ ] S3
- 어플리케이션을 활용한 fallback 방식

**Comment by Hwanvely** [comment]
@0chil  아이패드에 있는 그림 한번 올려주시면 감사하겠습니다!

**Comment by 0chil** [comment]
거의 피카쏘
![정리중-68](https://github.com/snack-game/server/assets/39221443/0a5c087f-a641-4999-ab66-3dbbc0bc1e51)

**Comment by 0chil** [comment]
당장은 운영에 영향이 없어 일단 보류
