### ISSUE TITLE
연혁 만들기

### ISSUE THREAD

**Issue by 0chil** [snack-game/server#168]
언제 시작해서, 지금까지 무엇을 했고, 어떤 변화들이 있었는지 연혁을 작성한다

**Comment by 0chil** [comment]
연혁을 작성해 봤는데요.
더딘것 같았지만 매달 큰 거 한 건씩은 했더라구요 😄
현생도 바쁠텐데 우리 팀원들 모두 칭찬합니다 💯💯💯 @dev-dong-su @nijuy @Hwanvely 

연혁은 `24/9/30`에 블로그 소개 부분에 올릴 예정입니다 🙇🏻
추가하거나 수정하고 싶은 내용은 [Notion](https://www.notion.so/10700ca278ab80d1b0d7dc3dbd58e011?pvs=4)에 작성해주시면 감사드리겠습니다 :)
사진을 추가하거나 날짜를 수정해주셔도 좋아요.

**Comment by nijuy** [comment]
무조건 박수갈채......... 참잘했어요 백만스물한개.....🤸‍♀️🎉💛
