### ISSUE TITLE
사과게임 DDL 오류

### ISSUE THREAD

**Issue by 0chil** [snack-game/server#173]
<img width="999" alt="image" src="https://github.com/user-attachments/assets/130f71dd-e5b4-4b43-8daa-64bd731f4074">

필드명이 모종의 이유로 달라졌나봅니다  
validation에 실패하고 있네요!

**Comment by Hwanvely** [comment]
제가 수정하긴 했어서 한번 확인해보겠습니다.

**Comment by Hwanvely** [comment]
운영서버 ddl 수정해 두었고 배포 완료했습니다!
