### ISSUE TITLE
랭킹 API 응답에 텍스트 압축을 적용한다

### ISSUE THREAD

**Issue by nijuy** [snack-game/server#191]
## 개요

3회 세미나에서 요청용 이슈 하나 만들어두겠다고 했던 그것입니다

## 요청 사항

- 선두 랭크 조회에 관한 랭킹 API 2개

  ![image](https://github.com/user-attachments/assets/6f2c1253-6dd6-4067-93c7-8955a3a82051)

- 응답 크기가 일정 기준을 넘어갈 때 텍스트 압축 적용

## 세부 사항

- 텍스트 압축 적용 기준

  - 응답의 원 크기가 1.4KiB 미만이면 압축하란 제안 자체를 안 함 ([출처](https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression?utm_source=lighthouse&utm_medium=devtools&hl=ko#how_lighthouse_handles_text_compression))

- 압축 방식
 
  요청 헤더의 `Accepted-Encoding` 필드를 통해 클라이언트에서 지원하는 방식을 서버에 알릴 수 있는데요!

  ![image](https://github.com/user-attachments/assets/4ad39d36-527c-416a-97c1-1934193e20ec)

  > 참고로 제가 아주 얕게 알기로는....
  > `gzip` : 컴퓨팅 리소스를 `brotli`에 비해 적게 사용
  > `brotli` : `gzip`보다 효율 굿굿

  혹시 어떤 방식이 가장 편하신지 (혹은 어떤 방식이 지금 서버에 적합한지..?) 궁금햐요
  
  **클라이언트 기준으로는 `zstd`만 제외**하면 될 거 같습니다 (사파리 지원이 안 됨)

**Comment by Hwanvely** [comment]
-  텍스트 압축 적용 기준 
   -  현재 응답 크기가 최소 55 Kib/s ~ 최대 88 Kib/s 인데 이 중에서 선택적으로 적용할 이유가 있을까요..?
   -  제 생각에는 1.4KiB 초과만 되면 적용해도 될것같습니다.
- 압축 방식
   - gzip 대비 brotli의 압축률은 높지만 압축 및 해제에 소요되는 로딩시간이 길다.
   - 큰 용량이 아닌 단순한 응답 + 동적 컨텐츠 인데 굳이 brotli가 필요할까..? 라고 생각합니다.

---

### 추가사항
   - 근데 적용하는 김에 프로필 이미지 압축도 필요한가요?? @nijuy

**Comment by nijuy** [comment]
> 제 생각에는 1.4KiB 초과만 되면 적용해도 될것같습니다.

굿
응답 크기 범위 확인했고, 여기서 선택적으로 적용할 이유 없어보인다는 말에 공감합니다

> 큰 용량이 아닌 단순한 응답 + 동적 컨텐츠 인데 굳이 brotli가 필요할까..? 라고 생각합니다.

굿굿
효율을 극단적으로 높여야 하는 상황까진 아니니까(?) 압축 및 해제에 드는 리소스를 고려한다면 gzip으로 가보는 것 동의합니다

> 근데 적용하는 김에 프로필 이미지 압축도 필요한가요??

흠.
지금 서버에서 주는 `profileImage`를 랭킹 페이지에서 아예 안 쓰고 있거덩요
그래서 지금 안 해도 되지 않을까~ 하는 쪽이에요 저는
랭킹 페이지에서 이미지를 사용하게 될 경우 그때 고려해도 괜찮을 거 같은데 어떠세여

**Comment by 0chil** [comment]
동의보검입니다
프사는 유진님 말대로 나중에 프사 뿌릴때 고려해보시죠! (아마 조만간이 될 듯!)

**Comment by 0chil** [comment]
+ 지금은 응답 압축의 효과를 실험하는 단계니까 다른 변인은 통제해주는게 좋겠네요!

**Comment by Hwanvely** [comment]
@nijuy 

먼저 개발서버 적용해두었습니다!

<img width="181" alt="스크린샷 2024-12-04 오후 12 36 04" src="https://github.com/user-attachments/assets/eb90e3c3-c919-480b-839c-e7854b7ee4d2">

설정목록은 아래와 같습니다.
- gzip_comp_level : 압축 정도
- gzip_min_length : 압축 적용할 최소 크기 
   -  위에서는 1.4KiB로 하기로 하였는데 nginx default 값이 2048 byte라고 하네요 그래서 수정하였습니다
- gzip_buffers : 버퍼의 숫자 / 크기  
- gzip_proxied : 프록시에 따른 동작 설정 
- gzip_type : 압축 컨텐츠 유형

---
적용된 것 같은데 확인부탁드리겠습니다! 
Swagger 에서 확인한 화면입니다

<img width="490" alt="스크린샷 2024-12-04 오후 12 38 12" src="https://github.com/user-attachments/assets/b2c18a8d-bd89-427b-a349-f8ac62358cb2">

**Comment by nijuy** [comment]
넵!! 제가 이동 중이라 노트북 쓸 수 있을때 바로 확인해볼게요 감사감사합니다 👩‍💻

**Comment by nijuy** [comment]
> 1.4KiB로 하기로 하였는데 nginx default 값이 2048 byte라고 하네요 그래서 수정하였습니다

여기 확인했어요! 상세한 설명에 따봉. 드립니다
기존에 lighthouse (성능 측정 툴) 에서 경고 뜨던 항목도 사라졌어요

| 전 | 후 |
|:---:|:---:|
| ![image](https://github.com/user-attachments/assets/dea446f1-6d0e-48d0-b1ad-6b5c3973ff0e)| ![image](https://github.com/user-attachments/assets/e6a54d3a-19b7-445d-99db-0a5f613fae11)|

좀 더 세부적으로 보여주는 툴로 재봤을 때, 랭킹 API 요청의 변경점은 아래와 같은데요

| 전 | 후 |
|:---:|:---:|
| ![image](https://github.com/user-attachments/assets/5171f820-7d91-4628-b1fa-05b022729479)| ![image](https://github.com/user-attachments/assets/713a0efe-a4fd-4876-9a59-197e58470343)|

서버 응답을 받기까지의 시간(Time To First Byte)이 줄어들면서
페이지 렌더링과 관련된 다른 지표도 약간씩 좋아졌다고 해석할 수 있을 거 같아요 
(다만 저 사이트가... 하루 사용량 제한이 있어서 기간을 두고 몇 번 더 재보려고 합니다)
 
저는 프로덕션 서버에도 동일하게 적용해봐도 될 거 같습니다!! ‎(っ ᵔ◡ᵔ)っ

**Comment by Hwanvely** [comment]
새벽에 prod 서버에도 적용해두었습니다! 😊
nginx 재실행시 중단 걱정으로 인해 혹시나해서 새벽에 진행하였는데 멍청한 판단이었습니다...
`restart`가 아닌 `reload`를 하면 shutdown이 되지 않더군요

**Comment by Hwanvely** [comment]
새벽에 prod 서버에도 적용해두었습니다! 😊
nginx 재실행시 중단 걱정으로 인해 혹시나해서 새벽에 진행하였는데 멍청한 판단이었습니다...
`restart`가 아닌 `reload`를 하면 shutdown이 되지 않더군요
